### ISSUE TITLE
如何获取插入记录的自增id？

### ISSUE THREAD

**Issue by octopuszy** [easy-swoole/mysqli#25]

**Comment by imparting** [comment]
$db->getInsertId();

**Comment by Sunshine40** [comment]
@imparting $db是什么类型的对象？我没有看到getInsertId()方法

比对了一下本项目和 https://github.com/ThingEngineer/PHP-MySQLi-Database-Class 的差异，这里的$stmt->insert_id在任何地方都没有机会暴露出来，是不是需要补充一下这个功能？
